/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Mensagem de erro */
            error?: string;
            /** @description Código do erro */
            code?: string;
        };
        HealthCheck: {
            /** @description Status de saúde do sistema */
            ok?: boolean;
            /**
             * Format: date-time
             * @description Timestamp da verificação
             */
            ts?: string;
            /** @description Versão do sistema */
            version?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
